Added task solution
Lessorg/BookShop pull request #11
Opened 2024-11-29 18:20 UTC by Lessorg

2024-11-30 14:55 UTC, sarakhmen requested changes
great job! Just a small improvement required

2024-11-30 14:55 UTC, sarakhmen commented on src/main/java/test/project/bookshop/repository/book/BookRepository.java
> +    Page<Book> findAllByCategories_Id(Long categoryId, Pageable pageable);
I'd recommend avoid using '_' within method names

2024-12-02 07:09 UTC, liliia-ponomarenko approved these changes
Good job! A few recommendations ;)

2024-12-02 07:09 UTC, liliia-ponomarenko commented on src/main/java/test/project/bookshop/controller/CategoryController.java
> +    @PostMapping
ResponseStatus.CREATED

2024-12-02 07:09 UTC, liliia-ponomarenko commented on src/main/java/test/project/bookshop/model/Category.java
> +public class Category {
Should it be a soft-deleted entity?

2024-12-02 07:09 UTC, liliia-ponomarenko commented on src/main/java/test/project/bookshop/dto/book/BookRequestDto.java
> +    private List<Long> categoryIds;
Can a book exist without Category? Let’s  use NotEmpty validation

2024-12-02 07:09 UTC, liliia-ponomarenko commented on src/main/java/test/project/bookshop/service/impl/BookServiceImpl.java
> +        Page<Book> bookPage = bookRepository.findAllByCategoriesId(id, pageable);
you can use the method `map` of Page and simplify this method

2024-12-02 13:39 UTC, merged