Initial commit
Lessorg/BookShop pull request #6
Opened 2024-11-07 15:25 UTC by Lessorg

2024-11-07 15:47 UTC, Elena-Bruyako requested changes
see comments

2024-11-07 15:47 UTC, Elena-Bruyako commented on src/main/java/test/project/bookshop/dto/BookDto.java
>  public class BookDto {
don't need to validate response

2024-11-07 15:47 UTC, Elena-Bruyako commented on src/main/java/test/project/bookshop/dto/BookRequestDto.java
> +    @NotNull
for String use

```suggestion
    @NotBlank
```

2024-11-07 15:47 UTC, Elena-Bruyako commented on src/main/java/test/project/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, headers, status);
```suggestion
        return new ResponseEntity<>(body, headers, HttpStatus.BAD_REQUEST);
```

2024-11-07 15:47 UTC, Elena-Bruyako commented on src/main/java/test/project/bookshop/exception/CustomGlobalExceptionHandler.java
> +
remove empty line

2024-11-08 18:26 UTC, okuzan approved these changes

2024-11-13 15:28 UTC, merged